Enhance API by avoiding macros
crystal-posix/ioctl.cr pull request #2
Opened 2023-02-02 23:28 UTC by j8r

This overhauls the library by changing macros to methods. This improves type safety and documentation, with no real downsides other than being a big breaking-change.

I've also added a non-raising method for `IOCTL.ioctl` , which yields a block. I think it is more idiomatic than returning `String | Nil`, with `String` being an error (!).

Finally, few tests were added, and verified that the results didn't change from the previous macros.

2023-02-02 23:57 UTC, postmodern reviewed
I just have some basic questions about some of the possible impacts of these changes.

2023-02-02 23:57 UTC, postmodern commented on LICENSE.txt
> +Copyright (c) 2023 Postmodern
Should be `2020-2023`.

2023-02-02 23:57 UTC, postmodern commented on src/ioctl.cr
> +      yield String.new(LibC.strerror(Errno.value))
I don't think I've ever seen this pattern of yielding a String as the error message. If we wanted to yield the error, instead of raising it, shouldn't we yield the `Error` object?

2023-02-02 23:57 UTC, postmodern commented on src/bits/ioctls.cr
> +  SIOCDELDLCI = 0x8981_u32 # Delete DLCI device
These stylistic changes could be extracted as a separate PR, as I have no problem with them.

2023-02-02 23:57 UTC, postmodern commented on src/ioctl.cr
> +  def ioctl(fd : LibC::Int, request : UInt32, *arguments, & : String ->) : Nil
What would be a use-case of calling `ioctl` with a block instead of rescuing the exception?

2023-02-02 23:57 UTC, postmodern commented on src/asm-generic/ioctl.cr
> +        (nr << IOC_NRSHIFT) | (size << IOC_SIZESHIFT)
Does the crystal compiler fully optimize the ioctl numbers down to constants, or will this result in needless method calls?

2023-02-02 23:57 UTC, postmodern commented on shard.yml
> -    version: "~> 0.9, >= 0.9.9"
Eh, I'm kind of a fan of spectator and RSpec style syntax. Although, I'm not actively working on this shard and it's basically feature complete at this point.

2023-02-03 00:59 UTC, j8r commented on src/ioctl.cr
> +      yield String.new(LibC.strerror(Errno.value))
That's also a good solution.

2023-02-03 00:59 UTC, j8r commented on src/bits/ioctls.cr
> +  SIOCDELDLCI = 0x8981_u32 # Delete DLCI device
It is due to `crystal tool format`.

2023-02-03 01:03 UTC, j8r commented on src/asm-generic/ioctl.cr
> +        (nr << IOC_NRSHIFT) | (size << IOC_SIZESHIFT)
We usually use this method in constants, which will only called once. Plus, it may be optimized by LLVM.
Even if not, integer math is **very** fast.

2023-02-03 01:04 UTC, j8r commented on shard.yml
> -    version: "~> 0.9, >= 0.9.9"
Maybe but for such few specs, I've seen more pros to just use the stdlib's spec than using an external lib.

2023-02-03 01:08 UTC, j8r commented on src/ioctl.cr
> +  def ioctl(fd : LibC::Int, request : UInt32, *arguments, & : String ->) : Nil
On my side I'd like to avoid raising then rescuing exceptions. I wanted to log any error then, return.

Having a variant returning an `Errno` may be better.

2023-02-03 01:12 UTC, j8r commented on src/ioctl.cr
> +      yield String.new(LibC.strerror(Errno.value))
Actually, not. Returning an exception without raising it rarelly done.
We could return an `Errno` though.

2023-02-03 01:14 UTC, j8r commented on src/ioctl.cr
> +      yield String.new(LibC.strerror(Errno.value))
Ho, and [Errno#message](https://crystal-lang.org/api/1.7.2/Errno.html#message%3AString-instance-method) can then be used.
Let's do that.

2023-02-03 05:28 UTC, postmodern commented on src/asm-generic/ioctl.cr
> +        (nr << IOC_NRSHIFT) | (size << IOC_SIZESHIFT)
I guess this would also allow defining dynamic ioctls at runtime, which might be useful.

2023-02-03 05:32 UTC, postmodern requested changes
Missed a spot in a spec description. I'll compromise on these changes. I can't think of a reason to keep the macros, although I kind of feel like these constants should be computed at compile-time.

2023-02-03 05:32 UTC, postmodern commented on spec/ioctl_spec.cr
> +      it "yield a message" do
Spec description needs updating now that `ioctl?` returns `Errno?`.

2023-02-03 05:32 UTC, postmodern commented on shard.yml
> -    version: "~> 0.9, >= 0.9.9"
I guess it brings `ioctl.cr` more inline with Crystal's stdlib.

2023-02-03 12:09 UTC, j8r commented on spec/ioctl_spec.cr
> +      it "yield a message" do
Oops, yes missed that last night.

2023-02-03 12:19 UTC, j8r commented
Be reassured I highly doubt there will be any performance impact, perhaps a little at program start? Won't be noticeable.
I was also not 100% about the API, do we mimics the C one with `IOCTL._IOC`, or do more like Crystal with `IOCTL.ioc`?

IMO it is still a low level library, can be useful to have the same method name even though it doesn't respect the Crystal standard.

2023-02-03 12:42 UTC, j8r commented
I'm also not sure about the `UInt32` return types, may be fine to use `Int32` everywhere?

2023-02-03 13:50 UTC, postmodern commented
@j8r the reason why I originally wrote them as macros was to mimic the original C code as closely as possible to make porting any C code (ex: `/usr/include/linux/videodev2.h`) to Crystal as easy as possible. Keeping them uppercase means less code reformatting.

Any time you're working with bitwise operations (aka logical operations, which are different from arithmetic operations), you should use an unsigned integer, as those bitwise operations may set the MSB which would make the integer negative. Also, apparently [C++11 allows unsigned int as the implicit type for binary, octal, or hexadecimal integer literals](https://en.cppreference.com/w/cpp/language/integer_literal)?

2023-02-03 14:09 UTC, j8r commented
Thanks for the explanation! Let's keep returning `UInt32` then, as before.

2023-02-04 03:11 UTC, postmodern requested changes
You're going to hate me, but I spotted another small typo in the docs.

2023-02-04 03:11 UTC, postmodern commented on README.md
> +  | `_IO`       | `iIOCTL::_IOC(type,nr)`         |
You're going to hate me, but you missed a spot. Extra `i` left over that I just noticed.

2023-02-04 03:13 UTC, postmodern commented
Oh yeah, another reason why the type of the IOCTL flags should always be unsigned, is the C declaration for `ioctl()` accepts an `unsigned long`. So flags should always be represented and passed as unsigned ints.

2023-02-04 13:13 UTC, j8r commented on README.md
> +  | `_IO`       | `iIOCTL::_IOC(type,nr)`         |
Good catch!

2023-02-04 13:19 UTC, j8r commented
I've added a little commit to update the CI, I can do in a separate PR if you prefer.
The CI doesn't run on this PR for some reasons.

2023-02-05 01:07 UTC, postmodern commented
We'll eventually need to figure out a `ioctl` that can be called in the CI, which runs head-less which prevents us from using the normal get terminal dimensions `ioctl`, thus causing the CI to fail.

2023-02-05 01:10 UTC, postmodern commented
Manually cherry-picked your two latest commits (sans the CI update) into `master`.

2023-02-05 01:10 UTC, closed without merging

2023-02-05 12:31 UTC, j8r commented
I'll make another PR then for the CI, thanks!

2023-02-12 15:55 UTC, j8r commented
Remains to create a git tag and we will be able to use the new version :slightly_smiling_face:

2023-02-13 00:04 UTC, postmodern commented
@j8r we may need to make a 1.1.0 release. I was writing up the release notes and noticed that the new class-methods do not map 1:1 with the old macros, and it looks like we're missing the `_IO` macro and the `_IO[RW]_BAD` macros. I want to keep the Crystal class-methods as 1:1 with the C macros to make it easy to port C code to Crystal.

2023-02-13 01:04 UTC, postmodern commented
Oops, I tagged the wrong commit. Forgot to `git pull` then `git tag`. Had to re-tag and `git push --tags -f`.

2023-02-13 14:07 UTC, j8r commented
What are this `_BAD` macros? I haven't seen them with `grep -r _BAD /usr/include/linux` and haven't seen them on the net.
And for `IOC`/`IOC`, I checked this are typos in the README.md, my bad - just remove the extra `C`.

2023-02-13 23:31 UTC, postmodern commented
@j8r I have the `_BAD_` macros in `/usr/include/asm-generic/ioctl.h`. According to Google they exist for [backwards compatibility](https://stackoverflow.com/questions/22021491/what-is-the-purpose-of-ior-bad-and-iow-bad) so as to not break things? Including them shouldn't hurt things since Crystal will just optimize out unused code.

2023-02-14 00:04 UTC, j8r commented
If they became aliases, in Crystal we usually avoid those.
Personally I was a bit confused at first why there were "bad" methods.
From what I've seen they perform less type checks in C.

I don't think it is a good idea to add them, they won't add anything but confusion.